services:
  loki:
    image: grafana/loki:3.1.1
    command: -config.file=/etc/loki/config.yml
    ports: ["3100:3100"]
    volumes:
      - ./dashboards/grafana/loki-config.yml:/etc/loki/config.yml:ro
      #- loki-data:/loki

  promtail:
    image: grafana/promtail:3.1.1
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./dashboards/grafana/promtail-config.yml:/etc/promtail/config.yml:ro
      - ./out:/logs:ro   # your JSONL directory

  grafana:
    image: grafana/grafana:11.2.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin1
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    ports: ["3000:3000"]
    depends_on: [loki]
    volumes:
      - ./dashboards/grafana/grafana-provisioning:/etc/grafana/provisioning

  producer:
    profiles: ["producer"]
    build:
      context: .
      dockerfile: Dockerfile.demo
    image: demo-sql-service-java
    volumes:
      - ./out:/app/out
    command:
      - "com.hazelcast.fcannizzohz.PaymentFlowToHazelcastCmd" # Class to run the main() of
      - "--disable-hazelcast"
      - "true"
      - "--cluster"
      - "dev" # pass the hz clusterName
      - "--member"
      - "hazelcast1:5701" # pass the hz member address
      - "--hours-past"
      - "2" # Start the simulated timeline N days in the past
      - "--rate"
      - "600" # 1 real second = 600 simulated seconds
      - "--min-tx-count"
      - "500"
      - "--gen-poll-sec"
      - "1"
      - "--output-dir"
      - "/app/out"

networks:
  default:
    name: hazelcast-net
